export const HARDCODED_DESCRIPTIONS: Record<string, { ru: string, uz: string, image_url: string }> = {
  "1": {
    image_url: '/images/tabiiy-non.jpg',
    ru: `🍞 Tabiiy non\n\n🌾 Tarkibi: Bug'doy uni, suv, tuz va xamirturish\n⚖️ Vazni: 550 gr\n💵 Narxi: 7 000 so'm\n\n✨ Foydali va shifobaxsh xususiyatlari:\n\nOson hazm bo‘ladi: Tabiiy xamirturish sababli oshqozonda og‘irlik va dam bo‘lishini keltirib chiqarmaydi.\n\nIchaklar uchun foydali: Ichak mikroflorasini yaxshilaydi va hazm tizimini tartibga soladi.\n\nQon shakarini me'yorda ushlaydi: Glyukozaning keskin ko‘tarilishini oldini oladi va uzoq vaqt to‘qlik hissini beradi.\n\nMinerallarga boy: Don tarkibidagi foydali elementlar va temirning organizmga oson so‘rilishiga yordam beradi.\n\n100% ziyonsiz: Tarkibida sun'iy kimyoviy qo‘shimchalar, drojji va konservantlar yo‘q.\n\nSog‘lom ovqatlanish va oshqozon-ichak tizimini asrash uchun eng yaxshi tanlov!`,
    uz: `🍞 Tabiiy non\n\n🌾 Tarkibi: Bug'doy uni, suv, tuz va xamirturish\n⚖️ Vazni: 550 gr\n💵 Narxi: 7 000 so'm\n\n✨ Foydali va shifobaxsh xususiyatlari:\n\nOson hazm bo‘ladi: Tabiiy xamirturish sababli oshqozonda og‘irlik va dam bo‘lishini keltirib chiqarmaydi.\n\nIchaklar uchun foydali: Ichak mikroflorasini yaxshilaydi va hazm tizimini tartibga soladi.\n\nQon shakarini me'yorda ushlaydi: Glyukozaning keskin ko‘tarilishini oldini oladi va uzoq vaqt to‘qlik hissini beradi.\n\nMinerallarga boy: Don tarkibidagi foydali elementlar va temirning organizmga oson so‘rilishiga yordam beradi.\n\n100% ziyonsiz: Tarkibida sun'iy kimyoviy qo‘shimchalar, drojji va konservantlar yo‘q.\n\nSog‘lom ovqatlanish va oshqozon-ichak tizimini asrash uchun eng yaxshi tanlov!`
  },
  "2": {
    image_url: '/images/miks-non.jpg',
    ru: `🍞 Miks non\n\n🌾 Tarkibi: Arpa uni, bug'doy uni, makkajo'xori uni, sabzi soki, tuz va xamirturish\n⚖️ Vazni: 600 gr\n💵 Narxi: 10 000 so'm\n\n✨ Foydali va shifobaxsh xususiyatlari:\n\nUch karra kuchli vitaminlar: Arpa, bug‘doy va makkajo‘xori unining aralashmasi organizmni barcha zarur minerallar va kletchatka bilan ta'minlaydi.\n\nKo‘z va teri uchun foydali: Tarkibidagi tabiiy sabzi soki vitamin A ga boy bo‘lib, ko‘rish qobiliyatini va immun tizimini mustahkamlaydi.\n\nModda almashinuvini yaxshilaydi: Arpa va makkajo‘xori uni ovqat hazm qilishni tezlashtiradi, qon tomirlarini tozalashga yordam beradi.\n\nUzoq vaqt to‘q tutadi: Murakkab uglevodlarga boy bo‘lgani uchun energiyani uzoq vaqt ushlab turadi va ortiqcha vazndan qochishga yordam beradi.\n\n100% tabiiy va toza: Sun'iy kimyoviy qo‘shimchalarsiz, faqat tabiiy mahsulotлардан tayyorlangan.\n\nSog‘lik va energiya manbai bo‘lgan haqiqiy vitaminlar miksi!`,
    uz: `🍞 Miks non\n\n🌾 Tarkibi: Arpa uni, bug'doy uni, makkajo'xori uni, sabzi soki, tuz va xamirturish\n⚖️ Vazni: 600 gr\n💵 Narxi: 10 000 so'm\n\n✨ Foydali va shifobaxsh xususiyatlari:\n\nUch karra kuchli vitaminlar: Arpa, bug‘doy va makkajo‘xori unining aralashmasi organizmni barcha zarur minerallar va kletchatka bilan ta'minlaydi.\n\nKo‘z va teri uchun foydali: Tarkibidagi tabiiy sabzi soki vitamin A ga boy bo‘lib, ko‘rish qobiliyatini va immun tizimini mustahkamlaydi.\n\nModda almashinuvini yaxshilaydi: Arpa va makkajo‘xori uni ovqat hazm qilishni tezlashtiradi, qon tomirlarini tozalashga yordam beradi.\n\nUzoq vaqt to‘q tutadi: Murakkab uglevodlarga boy bo‘lgani uchun energiyani uzoq vaqt ushlab turadi va ortiqcha vazndan qochishga yordam beradi.\n\n100% tabiiy va toza: Sun'iy kimyoviy qo‘shimchalarsiz, faqat tabiiy mahsulotлардан tayyorlangan.\n\nSog‘lik va energiya manbai bo‘lgan haqiqiy vitaminlar miksi!`
  },
  "3": {
    image_url: '/images/patir-non.jpg',
    ru: `🍞 Patir non\n\n🌾 Tarkibi: Oliy navli bug'doy uni, sariyog', sut, suv, tuz va xamirturish\n⚖️ Vazni: 700 gr\n💵 Narxi: 15 000 so'm\n\n✨ Foydali va shifobaxsh xususiyatlari:\n\nQuvvat baxsh etadi: Sariyog' va sut bilan qorilgan xamir uzoq vaqtga energiya beradi.\n\nYurak va qon tomirlariga foydali: Sut tarkibidagi kalsiy va sariyog' oqsillari organizmni mustahkamlaydi.\n\nMazza va kayfiyat: Qatlamali va xushbo'y ta'm asab tizimini tinchlantirib, kayfiyatni ko'taradi.\n\nBolalar uchun sevimli: Tabiiy sutli tarkibi suyaklarning o'sishi va rivojlanishiga yordam beradi.\n\n100% tabiiy: Faqatgina tabiiy sariyog' va toza sutdan foydalanib yopilgan haqiqiy o'zbek patiri!\n\nShohona dasturxonlarning ko'rki bo'lgan, mazzasi og'izda eriydigan patir non!`,
    uz: `🍞 Patir non\n\n🌾 Tarkibi: Oliy navli bug'doy uni, sariyog', sut, suv, tuz va xamirturish\n⚖️ Vazni: 700 gr\n💵 Narxi: 15 000 so'm\n\n✨ Foydali va shifobaxsh xususiyatlari:\n\nQuvvat baxsh etadi: Sariyog' va sut bilan qorilgan xamir uzoq vaqtga energiya beradi.\n\nYurak va qon tomirlariga foydali: Sut tarkibidagi kalsiy va sariyog' oqsillari organizmni mustahkamlaydi.\n\nMazza va kayfiyat: Qatlamali va xushbo'y ta'm asab tizimini tinchlantirib, kayfiyatni ko'taradi.\n\nBolalar uchun sevimli: Tabiiy sutli tarkibi suyaklarning o'sishi va rivojlanishiga yordam beradi.\n\n100% tabiiy: Faqatgina tabiiy sariyog' va toza sutdan foydalanib yopilgan haqiqiy o'zbek patiri!\n\nShohona dasturxonlarning ko'rki bo'lgan, mazzasi og'izda eriydigan patir non!`
  }
}
